[project]
name = "theater-scraper"
version = "0.1.0"
description = "Parses theater websites on schedule and serves data via API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
